version: '2.0'
services:
  sshd:
    image: skinnys/docker-sshd-otp
    container_name: sshd
    volumes:
      -  data/.google_authenticator:/.google_authenticator
      -  data/id_rsa.pub:/home/user/.ssh/authorized_keys 
    ports:
      - "2222:22"
